name: SonarQube Python Scan

on:
  push:
    branches:
      - main   
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: 5e3bf0a39e8526491795a7998f3bdf10c26ab976
          SONAR_HOST_URL: 'https://sonarcloud.io'
          
